
// Create a dictionary that stores the dog's scores (init at 0)
var dogScores = {
    akita: 0,
    berneseMountainDog: 0,
    bloodhound: 0,
    borzoi: 0,
    bullmastiff: 0,
    greatDane: 0,
    greatPyrenees: 0,
    irishWolfhound: 0,
    mastiff: 0,
    rottweiler: 0,
    saintBernard: 0,
    afghanHound: 0,
    boxer: 0,
    briard: 0,
    chesapeakeBayRetriever: 0,
    clumberSpaniel: 0,
    dobermanPinscher: 0,
    englishSetter: 0,
    germanShorthairedPointer: 0,
    germanWirehairedPointer: 0,
    giantSchnauzer: 0,
    goldenRetriever: 0,
    gordonSetter: 0,
    greyhound: 0,
    irishSetter: 0,
    labradorRetriever: 0,
    rhodesianRidgeback: 0,
    scottishDeerhound: 0,
    australianShepherd: 0,
    bassetHound: 0,
    beardedCollie: 0,
    borderCollie: 0,
    bullTerrier: 0,
    chowChow: 0,
    dalmatian: 0,
    englishSpringerSpaniel: 0,
    fieldSpaniel: 0,
    finnishSpitz: 0,
    irishWaterSpaniel: 0,
    keeshond: 0,
    kerryBlueTerrier: 0,
    pharaohHound: 0,
    pointer: 0,
    portugueseWaterDog: 0,
    saluki: 0,
    samoyed: 0,
    siberianHusky: 0,
    staffordshireBullTerrier: 0,
    vizsla: 0,
    welshSpringerSpaniel: 0,
    australianTerrier: 0,
    basenji: 0,
    beagle: 0,
    bedlingtonTerrier: 0,
    bichonFrise: 0,
    borderTerrier: 0,
    bostonTerrier: 0,
    cairnTerrier: 0,
    cavalierKingCharlesSpaniel: 0,
    dachshund: 0,
    frenchBulldog: 0,
    pug: 0,
    schipperke: 0,
    sealyhamTerrier: 0,
    shibaInu: 0,
    shihTzu: 0,
    skyeTerrier: 0,
    tibetanSpaniel: 0,
    tibetanTerrier: 0,
    whippet: 0,
    affenpinscher: 0,
    chihuahua: 0,
    italianGreyhound: 0,
    japaneseChin: 0,
    maltese: 0,
    papillon: 0,
    pomeranian: 0
};

// Now, we'll make the solutions for each question.
// The first question will be regarding the size of the dog
const sizeOption1 = []